### ISSUE TITLE
Accelerometer Calibration. 

### ISSUE THREAD

**Issue by jasvinder1079** [jremington/ICM_20948-AHRS#7]
Hi @jremington,
I went through your library and understand that, After collecting calibration data ,the python script you provided is for calibration will take data from csv files are provide calibrated data which we can use in get_scaled_IMU API and then we'll calibrated roll pitch and yaw. But the python scripts is for magnetometer only as per your code ,How accelerometer calibration is happening here?

**Comment by jasvinder1079** [comment]
One more thing,
If python code is there for calibration, Do we need to use Magneto.c file( is this also for calibration ?).
and others file like gravity_demo and icm_20948_tilt_compesation what's use of these ?

**Comment by jremington** [comment]
Magneto.c and calibrate3.py do the same thing, using different programming languages.

The file gravity_demo.ino calculates and returns the estimated direction of "down" in the sensor frame of reference, which is useful for subtracting the acceleration due to gravity from the total acceleration.  The tilt compensation code is a tilt-compensated magnetic compass, also for navigation.

**Comment by jasvinder1079** [comment]
And,
What about accelerometer calibration here ?
